branch-defaults:
  default:
    environment: ico-frontend
  master:
    environment: ico-frontend
environment-defaults:
  ico-frontend:
    branch: null
    repository: null
global:
  application_name: Kaicoin-ICO
  default_ec2_keyname: AwsKeyPair-GreenStage
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Node.js running
    on 64bit Amazon Linux/4.2.0
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
